# These are supported funding model platforms

github: johnpatrickroach
patreon: patrickroach
open_collective: betterwealth
ko_fi: patrickroach
tidelift: # Replace with a single Tidelift platform-name/package-name
community_bridge: # Replace with a single Community Bridge project-name
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.venmo.com/u/better-wealth', 'https://www.venmo.com/u/johnpatrickroach']
