# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
default_language_version:
  python: python3.7

default_stages: [commit, push]

exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: debug-statements
  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
  - repo: https://github.com/terrencepreilly/darglint
    rev: master
    hooks:
    - id: darglint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
