language: python
dist: xenial
virt: lxd
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
    - TWINE_USERNAME=johnpatrickroach
matrix:
  include:
    - python: '3.7'
      env:
        - TOXENV=check
    - python: '3.7'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py310-cover,codecov,extension-coveralls,coveralls
      python: '3.1'
    - env:
        - TOXENV=py310-nocov
        - WHEEL_MANYLINUX="1 cp310"
      python: '3.1'
    - env:
        - TOXENV=py37-cover,codecov,extension-coveralls,coveralls
      python: '3.7'
    - env:
        - TOXENV=py37-nocov
        - WHEEL_MANYLINUX="1 cp37"
      python: '3.7'
    - env:
        - TOXENV=py38-cover,codecov,extension-coveralls,coveralls
      python: '3.8'
    - env:
        - TOXENV=py38-nocov
        - WHEEL_MANYLINUX="1 cp38"
      python: '3.8'
    - os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - TOXENV=py39-cover
    - env:
        - TOXENV=py39-cover,codecov,extension-coveralls,coveralls
      python: '3.9'
    - os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - TOXENV=py39-nocov
        - WHEEL_PATH=.tox/dist
    - env:
        - TOXENV=py39-nocov
        - WHEEL_MANYLINUX="1 cp39"
      python: '3.9'
    - env:
        - TOXENV=pypy3-cover,codecov,extension-coveralls,coveralls
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-nocov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - python -mpip install --progress-bar=off twine tox-wheel -rci/requirements.txt
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - |
    (
    set -eux
    if [[ -n ${WHEEL_MANYLINUX:-} ]]; then
      docker run --rm --user $UID -v $(pwd):/code ionelmc/manylinux:manylinux$WHEEL_MANYLINUX
      tox --installpkg wheelhouse/*.whl -v
      export WHEEL_PATH=wheelhouse
    else
      tox -v
    fi
    if [[ -n ${WHEEL_PATH:-} ]]; then
      twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $WHEEL_PATH/*.whl
    fi
    )
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
notifications:
  email:
    on_success: never
    on_failure: always
