language: python
dist: xenial
virt: lxd
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
    - TWINE_USERNAME=johnpatrickroach
matrix:
  include:
    - python: '3.7'
      env:
        - TOXENV=check
    - python: '3.7'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py310-cover,codecov,extension-coveralls,coveralls
      python: '3.1'
    - env:
        - TOXENV=py310-nocov
        - WHEEL_MANYLINUX="1 cp310"
      python: '3.1'
    - env:
        - TOXENV=py37-cover,codecov,extension-coveralls,coveralls
      python: '3.7'
    - env:
        - TOXENV=py37-nocov
        - WHEEL_MANYLINUX="1 cp37"
      python: '3.7'
    - env:
        - TOXENV=py38-cover,codecov,extension-coveralls,coveralls
      python: '3.8'
    - env:
        - TOXENV=py38-nocov
        - WHEEL_MANYLINUX="1 cp38"
      python: '3.8'
    - os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - TOXENV=py39-cover
    - env:
        - TOXENV=py39-cover,codecov,extension-coveralls,coveralls
      python: '3.9'
    - os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - TOXENV=py39-nocov
        - WHEEL_PATH=.tox/dist
    - env:
        - TOXENV=py39-nocov
        - WHEEL_MANYLINUX="1 cp39"
      python: '3.9'
    - env:
        - TOXENV=pypy3-cover,codecov,extension-coveralls,coveralls
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-nocov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - python -mpip install --progress-bar=off twine tox-wheel -rci/requirements.txt
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - |
    (
    set -eux
    if [[ -n ${WHEEL_MANYLINUX:-} ]]; then
      docker run --rm --user $UID -v $(pwd):/code ionelmc/manylinux:manylinux$WHEEL_MANYLINUX
      tox --installpkg wheelhouse/*.whl -v
      export WHEEL_PATH=wheelhouse
    else
      tox -v
    fi
    if [[ -n ${WHEEL_PATH:-} ]]; then
      twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $WHEEL_PATH/*.whl
    fi
    )
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
notifications:
  email:
    on_success: never
    on_failure: always
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: johnpatrickroach
  password:
    secure: "bUDYHzpzAl6ugiXWt/g9QpYewlmbdY+K7orijTJEzRVh5rTLzLUHVj1nvTuaBvyXOaMxYfjv1JeDw/FnaVakEKl4m7zqeFycL9j7zcICKH++OA7nay+aXhXwUZfQnVSnedCBg75wZS2nHF4nHplr5Q6POvp6qsT+B8XVUNvw+5u+2nvugXeGydaPo1f4buf38nh0O4DwgbD2FaQRyjC1ldmyxI1p+Jzj18LCbwXEnPWTLkQM+OGHlYVGTgT/U+nkIaFSEk+raiebNhthyE29togZUHtyRgjoRLOlz/kaC8ta3StTQa4j7edddUYxa7ihVl+4N+Vtja91E/SFfKk2hQ1/ddMT6X5R/7iYtZkXE2bT3mPMhtZ731zIE3eC/Bi95EdaBIXd+XMSm/7QJCYzzRVKSgwn4lmjmujKn9u9r16crm4Lv2CSSnTYj+6Lshoa8O9tozkdFIym3F+yRKzzvLvcqCTUDGYSZuUu80pYdaZ/iOU8z18GpwnoMEOAbMjKN2LC6eEOoZHp2etUTA0uBnc6PBKbq8P8si6F5baJzUXjXODgG7cmXzkTIjYiz3QDFru+TPRokdXU4kg5iqulYkTJJJNHIHw/vNmO9Fz0CWY2F9iJqdshlDC7p+Xi+20OkiAnS29HiLBT8I5ShC6MXom+ocT1b3Nd5gWtkicV+wI="
  on:
    tags: true
    repo: johnpatrickroach/trending_homebrew
    python: 3.8