# pylint: disable=invalid-name
# -*- coding: utf-8 -*-

"""Configure the documents."""


import os
import traceback

DOCUMENTATION = 'trending-homebrew Documentation'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.doctest',
    'sphinx.ext.extlinks',
    'sphinx.ext.ifconfig',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx_autodoc_typehints',
    "sphinx_click",
    # Used to include .md files:
    'm2r2',
    "myst_parser",
]
autoclass_content = 'class'
autodoc_member_order = 'bysource'
autodoc_typehints = "description"
autodoc_default_flags = {
    'members': '',
    'undoc-members': 'code,error_template',
    'exclude-members': '__dict__,__weakref__',
}
# Set `typing.TYPE_CHECKING` to `True`:
# https://pypi.org/project/sphinx-autodoc-typehints/
set_type_checking_flag = False
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']
master_doc = 'index'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'
project = 'trending-homebrew'
year = '2023'
author = 'John Patrick Roach'
copyright_string = f'{year}, {author}'
try:
    from pkg_resources import get_distribution

    version = release = get_distribution('trending_homebrew').version
except ImportError as err:
    print(err)
    traceback.print_exc()
    version = release = '0.1.0'
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
add_module_names = False
todo_include_todos = False
autodoc_default_options = {
    'show-inheritance': True,
}
extlinks = {
    'issue': ('https://github.com/johnpatrickroach/trending-homebrew/issues/%s', '#'),
    'pr': ('https://github.com/johnpatrickroach/trending-homebrew/pull/%s', 'PR #'),
}
# on_rtd is whether we are on readthedocs.org
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd:  # only set the theme if we're building docs locally
    html_theme = 'sphinx_rtd_theme'
    html_theme_options = {
        'sidebar_collapse': False,
        'show_powered_by': False,
    }
html_static_path = ['_static']
htmlhelp_basename = 'trending_homebrewdoc'
html_use_smartypants = True
html_last_updated_fmt = '%b %d, %Y'
html_split_index = False
html_sidebars = {
    '**': [
        'searchbox.html',
        'globaltoc.html',
        'sourcelink.html',
        'about.html',
        'badges.html',
        'navigation.html',
        'moreinfo.html',
        'github.html',
        'searchbox.html',
    ],
}
html_short_title = f'{project}-{version}'
latex_documents = [
    (master_doc, 'trending_homebrew.tex',
     DOCUMENTATION,
     'John Patrick Roach', 'manual'),
]
man_pages = [
    (master_doc, 'trending_homebrew',
     DOCUMENTATION,
     [author], 1)
]
texinfo_documents = [
    (master_doc, 'trending_homebrew',
     DOCUMENTATION,
     author,
     'trending_homebrew',
     'One line description of project.',
     'Miscellaneous'),
]
napoleon_use_ivar = True
napoleon_use_rtype = False
napoleon_use_param = False
napoleon_numpy_docstring = False
